---
abstract: 'Perl extension for collecting information about the machine'
author:
  - 'Tassilo von Parseval <tassilo.von.parseval@rwth-aachen.de>'
  - 'Jens Rehsack <sno@NetBSD.org>'
build_requires:
  Test::More: '0.9'
configure_requires:
  Capture::Tiny: '0.06'
  Config::AutoConf: '0.23'
  ExtUtils::CBuilder: '0.27'
  ExtUtils::Constant: '0'
  ExtUtils::MakeMaker: '0'
  File::Basename: '0'
  File::Spec: '0'
  Text::ParseWords: '0'
  parent: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.98, CPAN::Meta::Converter version 2.142060'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Unix-Statgrab
no_index:
  directory:
    - t
    - inc
recommends: {}
requires:
  Carp: '0'
  File::Basename: '0'
  File::Path: '2.00'
  File::Spec: '0'
  perl: v5.8.1
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=List-MoreUtils
  license: http://dev.perl.org/licenses/
  repository: https://github.com/i-scream/Unix-Statgrab
version: 0.105_001
