---
abstract: 'Perl extension for collecting information about the machine'
author:
  - 'Tassilo von Parseval <tassilo.von.parseval@rwth-aachen.de>'
  - 'Jens Rehsack <sno@NetBSD.org>'
build_requires:
  Capture::Tiny: '0.06'
  Config::AutoConf: '0.19'
  ExtUtils::CBuilder: '0.27'
  Module::Build: '0.4000'
configure_requires:
  Config::AutoConf: '0.19'
  File::Copy: '0'
  Module::Build: '0.4000'
  parent: '0'
dynamic_config: 1
generated_by: 'Module::Build version 0.4205, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Unix-Statgrab
provides:
  Unix::Statgrab:
    file: lib/Unix/Statgrab.pm
    version: '0.104'
resources:
  license: http://dev.perl.org/licenses/
  repository: https://github.com/i-scream/Unix-Statgrab
version: '0.104'
